export enum MaintenanceStatus {
  MAINTENANCE_LOG_STATUS_CASE_OPEN = 'CASE_OPEN',
  MAINTENANCE_LOG_STATUS_PENDING = 'PENDING',
  MAINTENANCE_LOG_STATUS_APPROVED = 'APPROVED',
  MAINTENANCE_LOG_STATUS_REJECTED = 'REJECTED',
  MAINTENANCE_LOG_STATUS_DONE = 'DONE'
}
