name: Node.js CI (lint)

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn lint
